### ISSUE TITLE
Balance is always positive

### ISSUE THREAD

**Issue by Hbehrainwala** [jagratirathod/Project-for-Bank-mangement#1]
- Show Transaction behaviour i.e Withdrawal, Deposit, Transferred from and to.
- Create unique account no for every customer while signup.

**Comment by jagratirathod** [comment]
Restrict transfer to the own account -  https://github.com/jagratirathod/Project-for-Bank-mangement/pull/3/commits/f74e8294b15bf3a2728c9be0a60ae3d1ee17a080

**Comment by jagratirathod** [comment]
Show balance low error on the same form. -  
 https://github.com/jagratirathod/Project-for-Bank-mangement/pull/3/commits/e2e9c885edeae942f62c400124fddd4d73efefdf

**Comment by jagratirathod** [comment]
Manage balance after transaction field for every transaction i.e Deposit, Withdrawl and Transfer -

https://github.com/jagratirathod/Project-for-Bank-mangement/pull/3/commits/3a9deb718ee10df0b431e7313785616b9d22a60e

**Comment by jagratirathod** [comment]
unique account no for every customer while signup. - 
https://github.com/jagratirathod/Project-for-Bank-mangement/pull/3/commits/a207d811e96c738106c64f739eb5f483cd2698af

**Comment by Hbehrainwala** [comment]
https://github.com/jagratirathod/Project-for-Bank-mangement/pull/3
